// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTDMXWyTLaXR7KmOfo1IhRH7DZbOTyezc',
    appId: '1:75533475992:web:8fe3197945a3c35cd02c19',
    messagingSenderId: '75533475992',
    projectId: 'dreamcolor-1fd94',
    authDomain: 'dreamcolor-1fd94.firebaseapp.com',
    storageBucket: 'dreamcolor-1fd94.firebasestorage.app',
    measurementId: 'G-B0N7WVK1CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTDMXWyTLaXR7KmOfo1IhRH7DZbOTyezc',
    appId: '1:75533475992:android:c2b6c41d7c94440b37b0ed',
    messagingSenderId: '75533475992',
    projectId: 'dreamcolor-1fd94',
    storageBucket: 'dreamcolor-1fd94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0a_FDvJDSzNu3XDb_av7ry5nWH_tVSo',
    appId: '1:75533475992:ios:f53476275a97a87b37b0ed',
    messagingSenderId: '75533475992',
    projectId: 'dreamcolor-1fd94',
    storageBucket: 'dreamcolor-1fd94.firebasestorage.app',
    iosBundleId: 'com.dreamcolor.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0a_FDvJDSzNu3XDb_av7ry5nWH_tVSo',
    appId: '1:75533475992:ios:7f6b829f98e4265537b0ed',
    messagingSenderId: '75533475992',
    projectId: 'dreamcolor-1fd94',
    storageBucket: 'dreamcolor-1fd94.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTDMXWyTLaXR7KmOfo1IhRH7DZbOTyezc',
    appId: '1:75533475992:web:7fdfb30cc52dee50d02c19',
    messagingSenderId: '75533475992',
    projectId: 'dreamcolor-1fd94',
    authDomain: 'dreamcolor-1fd94.firebaseapp.com',
    storageBucket: 'dreamcolor-1fd94.firebasestorage.app',
    measurementId: 'G-ZJG5PE7TEX',
  );
}
